### ISSUE TITLE
Missing Footprint Library 

### ISSUE THREAD

**Issue by wel97459** [etxmato/COMiX-HighSpeedDirectConnect#1]
Could you include the footprint library that contains the card edge, it would be helpful for other projects.

**Comment by awasson** [comment]
Hey Winston,
I just exported and pushed the footprint to the Github repo. 

Let me know if you have any trouble with it. It is the first footprint I've created and I need to rename/renumber the footprint conductors because it should have 1-22 on one side and A-Z on the other to match with the COMiX-35 edge connector but I have it alternating 1-44. At some point I plan to update it with the correct 1-22 / A-Z designations but is should save you some effort right off the bat. 

Cheers,
Andrew

**Comment by wel97459** [comment]
awesome thanks!

**Comment by wel97459** [comment]
oops
